### ISSUE TITLE
Markdown formatting in Readme.md

### ISSUE THREAD

**Issue by kunzel** [strands-project/strands_morse#10]
Does anybody know why the Markdown code elements such as '$ rosrun ...' are not visualized properly in the Readme.md? Or is the formatting wrong?

**Comment by marc-hanheide** [comment]
I corrected it in 835808c52498f969bedad42acd10f246532e804b
You just missed an additional space in your indentation. Because you ha an enumeration (one level indented), for source formatting you need 8 spaces... markdown is a bit strange, you know.
