### ISSUE TITLE
Unable to run lift_controller.py: rospy not available for python3?

### ISSUE THREAD

**Issue by koenlek** [strands-project/strands_morse#122]
Hi all,

I installed strands desktop full from your official repositories (`sudo apt-get install ros-indigo-strands-desktop`). Then I tried to get a simulation with the lift based on this wiki page:
https://github.com/strands-project/strands_morse/wiki/BHAM-Morse

With some effort, I got PySide compiled (removed 3 refs to sphinx.ext.refcounting, and in setup.py I changed line 235 to `filename = os.path.join(self.prefix, "local/bin", "pyside_postinstall.py")`)  . Also, I had to run:
`sudo chmod +x /opt/ros/indigo/share/strands_morse/bham/src/lift_controller.py`

The morse simulation starts fine:
`roslaunch strands_morse bham_cs_morse.launch env:=cs`

But starting the lift controller results in an error:
`rosrun strands_morse lift_controller.py`

It outputs:

```
$ rosrun strands_morse lift_controller.py
Traceback (most recent call last):
  File "/home/koenlek/strands_ws/src/strands_offical/strands_morse/bham/src/lift_controller.py", line 16, in <module>
    import rospy
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ImportError: No module named 'rospkg'
```

I think the issue is that rospy isn't available for python 3. How do you guys overcome this issue, because I can't find the solution anywhere. I also tried to check out the strands_morse repo and compile it in a catkin ws, but I still have the same issue...

My system is Ubuntu 14.04 with latest updates. Indigo with latest updates. python 3.4.

**Comment by hawesie** [comment]
rospy is available for Python 3, but you need to install it manually e.g.
- `sudo pip3 install rospkg`

or
- http://www.openrobots.org/morse/doc/1.2/user/installation/mw/ros.html#troubleshooting

**Comment by koenlek** [comment]
Thanks, apparently I needed to install these as well:

```
sudo pip3 install catkin_pkg
sudo pip3 install pymorse
```

Now it works!
