### ISSUE TITLE
multi-robot sim

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_morse#129]
I want to simulate 2 Bobs in morse. I want them to use a single roscore so I can use the ROS stuff for inter robot communication.

Does anyone have experience on how to setup such a simulation? Thanks.

**Comment by kunzel** [comment]
This will require to change some of the default topics used by Bob. I It should be relatively easy to make those optional parameters when you create the robot....f it is not urgent we can talk about it next week.

**Comment by bfalacerda** [comment]
cool, we'll talk next week then
