### ISSUE TITLE
Update laser position to match URDF

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_morse#143]
The position of the laser needs updating to match the actual robot's laser position. 

https://github.com/strands-project/strands_morse/blob/indigo-devel/strands_sim/src/strands_sim/builder/robots/scitosA5.py#L91

**Comment by marc-hanheide** [comment]
Who's doing this? @kunzel ?

**Comment by cburbridge** [comment]
I updated the laser pose, but we need to test it some more. Can Jenkins run the tests using a PR on this repo?

**Comment by marc-hanheide** [comment]
If there would be tests defined for this repo... I think there aren't.
