### ISSUE TITLE
use strands_movebase for all environment launch files

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_morse#144]
as agreed in a hangout on https://github.com/strands-project/strands_movebase/issues/62

**Comment by bfalacerda** [comment]
there's probably nothing to do here, unless you're using the nav files in strands_morse to launch navigation (e.g., https://github.com/strands-project/strands_morse/blob/indigo-devel/bham/launch/bham_cs_nav2d.launch)

If you're using `roslaunch strands_bringup strands_navigation.launch` for the simulation tests then once we merge https://github.com/strands-project/strands_movebase/pull/69 we will be using strands_movemase params in sim.

According to @kunzel we can just remove the nav2d launmch files from the repo, as they are not really needed anymore
