### ISSUE TITLE
Simplified CS model

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_morse#2]
The multi-floor CS model is cool, but I find it a bit hard to navigate and view. Please could we have a single-floor version for initial use?

**Comment by cburbridge** [comment]
I agree a multi-floor model is bordering on impossible to navigate. I think the best option is to still stick to a single model, but to setup some better controls for navigation. For example a menu of pre-defined camera poses and the possibility to temporarily hide floors from view. I'll look into it...

**Comment by hawesie** [comment]
Yep, floor visibility and camera controls would also be a good solution.

**Comment by cburbridge** [comment]
I have added component hiding to the main morse simulator. Check out and install the latest version development version, run it and then run morse/bin/morse_inspector.py to change floor visibility.

**Comment by hawesie** [comment]
Latest version of MORSE, or of the bham simulation?

**Comment by kunzel** [comment]
It is in the latest version of MORSE

## 

Lars Kunze

Research Fellow in Intelligent Robotics
School of Computer Science
University of Birmingham
http://www.cs.bham.ac.uk/~kunzel

**Comment by hawesie** [comment]
Great, thanks!
