### ISSUE TITLE
Battery and charging model for scitos robot in sim

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_morse#27]
Add battery model to robot and define charging point in existing sim models (perhaps these should be additional issues).

**Comment by kunzel** [comment]
@gestom Is there a way to enable a more verbose debug mode or something to see why the process fails?
I got the following:

```
    [ INFO] [1375111478.818290718]: Charging service is idle
    [ INFO] [1375111480.506095356]: Charging service is measuring the robot positition relatively to the ROBOT           STATION banner
    [ INFO] [1375111490.697644528]: Charging service is has failed to reach the charger
    [ INFO] [1375111491.040790852]: Charging service is idle
```

I'd assume that the image cannot really be detected, though I am not sure.

**Comment by kunzel** [comment]
Added in #45
