### ISSUE TITLE
Floating robot in bham_cs_morse

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_morse#37]
When I run `roslaunch strands_morse bham_cs_morse.launch` I get a floating robot. Does anyone see this? Any idea where I should start looking for the problem?

![screen shot 2013-07-23 at 22 21 59](https://f.cloud.github.com/assets/927289/852634/a1198912-f4b7-11e2-9285-70261c6e92de.png)

**Comment by kunzel** [comment]
Yes, I have it too. It's a missing physics parameter in the blender file.
I'll fix it today. As a workaround you might use the old (red) robot. Or
adjust the  starting position of the robot.
