### ISSUE TITLE
scitos_drivers topics and services in MORSE

### ISSUE THREAD

**Issue by kunzel** [strands-project/strands_morse#44]
As other components such as the autonomous docking and patrolling rely more and more on the topics and services provided by the scitos_drives package they become incompatible with the simulation.   

In the end we want to run the same control program on both the real robot and the simulated one.  So, basically all topics and services should also be provided by the simualtion. 

@cburbridge, do you have a good idea how to provide the services regarding the motor?

**Comment by marc-hanheide** [comment]
maybe it would be useful to have a dedicated Scitos ROS node that implements the same interface as the real robot. That means it mediates the MORSE topics (which should then be in a dedicated namespace) and adds more topics/services as needed. We could actually try to have this component implement the same interface as the Scitos_drivers themselves... Just ideas, though.
