### ISSUE TITLE
Discrepancies of the vision output

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_morse#49]
I would like to test the people detection in simulation as well, so I had a look at what morse is offering. It seems there are a few discrepancies:
- The image size , encoding and frame_id are different:

Kinect:

``` python
header: 
  seq: 580271
  stamp: 
    secs: 1376906509
    nsecs: 211710102
  frame_id: /head_xtion_rgb_optical_frame
height: 480
width: 640
encoding: bgr8
is_bigendian: 0
step: 1920
data: [...]
```

Morse:

``` python
header: 
  seq: 8502
  stamp: 
    secs: 1376906403
    nsecs: 950938940
  frame_id: /head_xtion_rgb_optical_frame/base_image
height: 256
width: 256
encoding: rgba8
is_bigendian: 0
step: 1024
data: [...]
```
- The camera info differs: (probably due to the different image sizes?!)

Kinect:

``` python
header: 
  seq: 7767413
  stamp: 
    secs: 1376907007
    nsecs: 114224
  frame_id: /head_xtion_rgb_optical_frame
height: 480
width: 640
distortion_model: plumb_bob
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [525.0, 0.0, 319.5, 0.0, 525.0, 239.5, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [525.0, 0.0, 319.5, 0.0, 0.0, 525.0, 239.5, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```

Morse:

``` python
header: 
  seq: 3426
  stamp: 
    secs: 1376906989
    nsecs: 161215782
  frame_id: /head_xtion_rgb_optical_frame/base_image
height: 256
width: 256
distortion_model: plumb_bob
D: []
K: [280.0, 0.0, 128.0, 0.0, 280.0, 128.0, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [280.0, 0.0, 128.0, 0.0, 0.0, 280.0, 128.0, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```
- The depth image is missing. Just the point cloud is published. Is there a way to provide this in morse?
- And of course issue #48 

If any one knows how to fix this the easiest, I am happy to provide help where I can because I think I am not the only one who would needs this kind of data in the future.

**Comment by hawesie** [comment]
I think @kunzel is probably your man for this, but he's on vacation for the next 2 weeks.

**Comment by cdondrup** [comment]
Thank you for letting me know.

**Comment by cdondrup** [comment]
@kunzel we talked about that issue briefly on Friday. Maybe we can have a look at it together.

**Comment by kunzel** [comment]
Hi @cdondrup, we can easily change the dimension of the RGB image to 640x480. In the latest version the alpha channel was already removed in the image encoding. So, you have something like this for the camera info:

```
header: 
  seq: 1
  stamp: 
    secs: 1381162175
    nsecs: 129631280
  frame_id: /head_xtion_rgb_optical_frame/base_image
height: 480
width: 640
encoding: rgb8
is_bigendian: 0
step: 1920
```

The encoding is still a little bit different (rgb8 instead of bgr8).  Would this be OK?

For the depth image, I will try to add the 'DepthVideoCamera' (http://www.openrobots.org/morse/doc/stable/_modules/morse/sensors/depth_camera.html) in MORSE. This should give you directly the depth image. 

I'll also try to generate a grayscale image in MORSE. So, that we have both topics: image_color and image_mono.

**Comment by cdondrup** [comment]
That's great news. Thank you!
The encoding is no problem. I can just write a simple node to re-encode the images into bgr8 to simulate the real asus. Also creating a mono image from the colour image should be easily done with a simple node if you can't do it in Morse directly.

**Comment by nilsbore** [comment]
@kunzel I've had a closer look at this now. I'm able project the point clouds to create `/head_xtion/depth/image_raw` and together with some changes to how the point cloud and rgb image are generated, this enables me to generate most of the topics from the openni_wrapper processing pipeline. However, for some reason, it keeps on crashing when I subscribe to the registered(aligned) topics, i.e. `/head_xtion/depth_registered/image_raw` or `/head_xtion/depth_registered/points`. I have to debug this more, possibly with the help of @RaresAmbrus , who worked on the openni_wrapper pipeline.

**Comment by nilsbore** [comment]
I guess this is also fixed by https://github.com/strands-project/strands_morse/pull/68, except for the part that @cdondrup mentioned about one being rgb8 and the other rgb8.
