### ISSUE TITLE
Ptu unit in simulation

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_morse#55]
Is there any way to move the PTU unit in simulation?

**Comment by kunzel** [comment]
Yes, it is. You just publish a message of type sensor_msgs/JointState to the topic named '/ptu_jointstate'.
I've just corrected the topic name in the latest version of the topic_republisher (strands_utils) to '/ptu/cmd' to reflect the topic name of the real robot.  That is, if you get the latest version of strands_morse and strands_utils it should work as on the real robot. 

Example:

$ rostopic pub /ptu/cmd sensor_msgs/JointState "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
name: ['pan','tilt']
position: [0.5, 0.5]
velocity: [0.5, 0.5]
effort: [0.5, 0.5]"

**Comment by Jailander** [comment]
Hi Lars,

I can move the PTU when I publish to /ptu_jointstate but not when I do it to /ptu/cmd I have updated my system a few minutes ago, any ideas?

cheers

**Comment by kunzel** [comment]
Hmm, did you also update strands_utils as I said above? The following commit should have actually changed the topic name to /ptu/cmd: https://github.com/strands-project/strands_utils/commit/bd66a3e36f0d4c589710169000d3f2fe5a118cc2

**Comment by Jailander** [comment]
Hi, problem solved I had some residual executables in my catkin_ws (things that happen when you are in a hurry). PTU works perfectly in simulation, thanks!

**Comment by kunzel** [comment]
Great, thanks for reporting the problem. I did not notice that the docking also uses the PTU in the meantime. Can you please check whether the docking is more stable now in simulation?

**Comment by Jailander** [comment]
Docking is working perfectly, I haven’t had any problems with it, the undocking part is the problem right now, since it is not working as it does on the robot, @gestom and I will look into it this afternoon. And I will let you know as soon as we have a fix.
