### ISSUE TITLE
morse-blender should be a dependency of strands_morse

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_morse#74]
This package should depend on the actual `morse-blender-2.65-py-3.3` as a run dependency.

**Comment by cdondrup** [comment]
Closed via #76

**Comment by cdondrup** [comment]
See 1176b524bbca81efd1dee3aaae1c7291d9f8eb3b

**Comment by kunzel** [comment]
@cdondrup Can we close this issue? I assume it has been solved with the release stuff, or not?
