### ISSUE TITLE
move_base not working in uol_mht environment

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_morse#77]
Some people reported to have problems with `move_base` in the uol mht environment. The robot would only spin in place but never move. I cannot reproduce the error but maybe someone has an idea? @kunzel maybe?

**Comment by hawesie** [comment]
Does teleop work? You can use http://wiki.ros.org/teleop_twist_keyboard if you don't have a pad handy. I've had problems with the robot getting stuck on the floor in sim. Some movements are possible, but not all.

**Comment by cdondrup** [comment]
@santosj can you please try that when you have some time?
You just have to install `ros-hydro-teleop-twist-keyboard` first and then run the simulation and `rosrun teleop_twist_keyboard teleop_twist_keyboard.py`

**Comment by cdondrup** [comment]
You were absolutely right @hawesie. See above PR.
Thank you!

**Comment by cdondrup** [comment]
This has been fixed.
