### ISSUE TITLE
scitos_description dependency missing

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_morse#84]
this should be a `<run_depend>`

**Comment by marc-hanheide** [comment]
and include morse-blender-bundle as run_depend, too

**Comment by cdondrup** [comment]
The `scitos_description` is already there: https://github.com/strands-project/strands_morse/blob/hydro-devel/package.xml#L53 Not sure why it wasn't installed when the student tried it.
But I will reintroduce the `morse-blender-bundle` since fedro versions are now not built any more.

**Comment by cdondrup** [comment]
Closed via #86
