### ISSUE TITLE
morse in 14.04

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_morse#91]
we haven't released this package for indigo yet, and `sudo apt-get install morse-blender-2.65-py-3.3` doesnt work in 14.04 either. Anyone knows how to get morse properly installed in 14.04?

**Comment by hawesie** [comment]
If we want to get the Indigo / 14.04 update process going, having a simulator we can test in is pretty important. Please can whoever created the Hydro / 12.04 package for strands morse prioritise this if possible?

**Comment by bfalacerda** [comment]
Can someone take a look at this @marc-hanheide ? @cdondrup ? I just need a trusty entry in our rosdep file for this morse-blender bundle, I'm happy to keep strands_morse in my local workspace for the time being.

**Comment by marc-hanheide** [comment]
OK, I can look into this, but not today and tomorrow. It's build using https://github.com/strands-project/dh_bin_wizard and I think @cburbridge might have used this repo to create the MIRA packages, so he might be quicker than me.

**Comment by marc-hanheide** [comment]
That said, the setup script for morse (https://github.com/strands-project/dh_bin_wizard/blob/dh_make/morse-setup.sh) pulls the latest HEAD form the morse repo. We shouldn't do that, I suppose, but rather pull a specific tag, that should then be reflected in the version number of the package, see https://github.com/strands-project/dh_bin_wizard/blob/dh_make/morse-strands.mk

**Comment by cburbridge** [comment]
I will try to look at this tomorrow.

**Comment by cburbridge** [comment]
I have made a package for our MORSE fork, it should get to the lincoln repo shortly. In the meantime you can download the .deb here: https://docs.google.com/file/d/0B-hS5kcbiUI8QU85VXExVXBXQUk/edit?usp=drive_web

Once MORSE is in the repo I will release strands_morse for indigo. In the meantime, after installing the above deb you can run morse on indigo by using the indigo-devel branch of this repo.

**Comment by bfalacerda** [comment]
the deb file works and everything runs, thanks!

There's an issue with move base but i'll open a new issue about it
