### ISSUE TITLE
morse-blender package not found

### ISSUE THREAD

**Issue by mzillich** [strands-project/strands_morse#94]
The morse-blender package can not be found:

```
sudo apt-get install morse-blender-2.65-py-3.3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package morse-blender-2.65-py-3.3
E: Couldn't find any package by regex 'morse-blender-2.65-py-3.3'
```

Am I missing a repository entry?

**Comment by marc-hanheide** [comment]
nope, it doesn't exist in trusty as we are using the official morse package here. @cburbridge knows more. Why did you try to install it?

**Comment by mzillich** [comment]
I followed the wiki instructions at https://github.com/strands-project/strands_morse. And I thought it would be necessary, cause running 

> roslaunch strands_morse bham_cs_morse.launch

gave an error that I have not quite figured out yet:

```
Running morse on /opt/ros/indigo/share/strands_morse/bham with PYTHONPATH=/opt/ros/indigo/share/strands_morse/bham/src:/opt/ros/indigo/share/strands_morse/strands_sim/src:/home/mz/work/SQUIRREL/code/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages and MORSE_RESOURCE_PATH=/opt/ros/indigo/share/strands_morse:/opt/ros/indigo/share/strands_morse/strands_sim/data:/opt/ros/indigo/share/strands_morse/strands_sim/robots:/opt/ros/indigo/share/strands_morse/bham/data:
* Using environment <bham>.

* Adding </opt/ros/indigo/share/strands_morse/bham> to PYTHONPATH and MORSE_RESOURCE_PATH.

* Loading simulation </opt/ros/indigo/share/strands_morse/bham/cs_lg.py>.

* morse 1.2

Color management: using fallback mode for management
connect failed: No such file or directory
read blend: /opt/strands-morse-simulator/share/morse/data/morse_default_autorun.blend
Color management: image colorspace "Raw" not found, will use default instead.
strands_sim.robots.scitosA5.Scitosa5: no interfaces available for this component! Check builder/data.py.
[ERROR][MORSE] Uncaught exception, quit Blender.
Traceback (most recent call last):
  File "/opt/ros/indigo/share/strands_morse/bham/cs_lg.py", line 17, in <module>
    robot = Scitosa5()
  File "/opt/ros/indigo/share/strands_morse/strands_sim/src/strands_sim/builder/robots/scitosA5.py", line 75, in __init__
    self.battery = BatteryStateSensor()
NameError: name 'BatteryStateSensor' is not defined
Traceback (most recent call last):
  File "/opt/ros/indigo/share/strands_morse/bham/cs_lg.py", line 17, in <module>
    robot = Scitosa5()
  File "/opt/ros/indigo/share/strands_morse/strands_sim/src/strands_sim/builder/robots/scitosA5.py", line 75, in __init__
    self.battery = BatteryStateSensor()
NameError: name 'BatteryStateSensor' is not defined
[strands_morse-6] process has died [pid 8399, exit code 255, cmd /opt/ros/indigo/lib/strands_morse/simulator.sh bham cs_lg.py __name:=strands_morse __log:=/home/mz/.ros/log/319aba66-a2df-11e4-9b95-fcf8ae0fd83b/strands_morse-6.log].
log file: /home/mz/.ros/log/319aba66-a2df-11e4-9b95-fcf8ae0fd83b/strands_morse-6*.log
```

**Comment by kunzel** [comment]
@marc-hanheide , aren't we using the package strands-morse-simulator in trusty? (this should be the STRANDS version if I am right). However, if we are going to use the standard Morse version (which would be OK with me), we have to make some minor changes to our robot model as their is, e.g. no BatteryStateSensor in Morse (see @mzillich 's error).

**Comment by cburbridge** [comment]
We now have two debian packages related to Morse:
- strands-morse-simulator: Our fork of the morse simulator  (Installed by `apt-get install strands-morse-simulator`). This includes our changes for BatteryState an includes ROS transport which the Ubuntu provided version does not have.
- strands-morse: A ROS package with our scenes and robot model. (Installed by `apt-get install ros-indigo-strands-morse`)

Overall it is now tidier than before. Previously we had to install a newer version of Blender, but now we can use the Ubuntu packaged version. Likewise, we has to install a newer version of Python 3, but now we use the Ubuntu packages for that.

**Comment by marc-hanheide** [comment]
Thanks for clarifying this. So @mzillich no need to install that package. If you install `apt-get ros-indigo-strands-desktop` you should get all the dependencies including morse automatically. If this doesn't work please reopen this ticket.

**Comment by ferdianjovan** [comment]
I know this topic is closed, but I am having the same problem.
I had strands_morse running until I installed standard-Morse following this 
http://www.openrobots.org/morse/doc/latest/user/installation/mw/ros.html

Even though I have un-installed standard Morse, and re-installed the whole strands-system, I still can not solve this problem. 

Is there a way to solve this problem?

**Comment by ferdianjovan** [comment]
The problem is solved, thanks to @cburbridge!

**Comment by cdondrup** [comment]
Is this a general problem? How was it solved? Is there a new release?

**Comment by ferdianjovan** [comment]
I do not know if this is a general problem. There was a package named python3-morse-<something> that had not been un-installed. In my case autoremove did not help after I un-installed standard morse.

**Comment by cburbridge** [comment]
The released version is fine, the problem is just a confusion as to how to
install the STRANDS-MORSE simulator. The desktop install includes it, or it
can manually be installed (pkg: ros-indigo-strands-morse). However, if you
install the non-strands MORSE packages provided by Ubuntu (pkg:
morse-simulator) then they will interfere. In this case, Ferdian had
installed Ubuntu-Morse in addition to strands-morse, then realised he
needed to remove ubuntu-morse. Removing ubuntu-morse left behind the python
bindings for ubuntu-morse, which took precedence over the strands-morse
python library. It was solved by removing the `python3-morse-simulator`
package as well as `morse-simulator`.
